export const user = {
  id: 1,
  name: "Vincenzo Nunziata",
  img: "https://github.com/lifeisfoo.png",
};

export const data = [
  {
    id: 1,
    list: "Film",
    todo: [
      { id: 1, name: "Mad Max: Fury Road", done: false },
      { id: 2, name: "John Wick", done: false },
      { id: 3, name: "The Dark Knight", done: false },
      { id: 4, name: "Die Hard", done: false },
      { id: 5, name: "Gladiator", done: true },
      { id: 6, name: "The Shawshank Redemption", done: false },
      { id: 7, name: "Forrest Gump", done: false },
      { id: 8, name: "Schindler's List", done: false },
      { id: 9, name: "The Godfather", done: true },
      { id: 10, name: "Fight Club", done: false },
      { id: 11, name: "The Big Lebowski", done: false },
      { id: 12, name: "Groundhog Day", done: false },
      { id: 13, name: "Monty Python and the Holy Grail", done: false },
      { id: 14, name: "Superbad", done: false },
      { id: 15, name: "The Grand Budapest Hotel", done: false },
      { id: 16, name: "Inception", done: false },
      { id: 17, name: "Blade Runner 2049", done: false },
      { id: 18, name: "Interstellar", done: true },
      { id: 19, name: "The Matrix", done: false },
      { id: 20, name: "2001: A Space Odyssey", done: false },
    ],
  },
  {
    id: 2,
    list: "Studiare",
    todo: [
      { id: 1, name: "Matematica", done: false },
      { id: 2, name: "Fisica", done: false },
      { id: 3, name: "Chimica", done: false },
      { id: 4, name: "Informatica", done: true },
      { id: 5, name: "Biologia", done: false },
      { id: 6, name: "Storia", done: false },
      { id: 7, name: "Geografia", done: false },
      { id: 8, name: "Filosofia", done: false },
      { id: 9, name: "Economia", done: false },
      { id: 10, name: "Letteratura", done: false },
    ],
  },
  {
    id: 3,
    list: "Viaggi",
    todo: [
      { id: 1, name: "Giappone - Esplorare Tokyo e Kyoto", done: false },
      { id: 2, name: "Italia - Visita a Roma, Venezia e Firenze", done: true },
      {
        id: 3,
        name: "Australia - Scoprire Sydney e la Grande Barriera Corallina",
        done: false,
      },
      { id: 4, name: "Islanda - Ammirare l'aurora boreale", done: false },
      { id: 5, name: "Perù - Escursione a Machu Picchu", done: false },
      {
        id: 6,
        name: "Thailandia - Relax sulle spiagge di Phuket e Koh Samui",
        done: false,
      },
      {
        id: 7,
        name: "Sudafrica - Safari nel Kruger National Park",
        done: false,
      },
      {
        id: 8,
        name: "Francia - Visitare Parigi e la regione della Provenza",
        done: false,
      },
      { id: 9, name: "Canada - Esplorare le Montagne Rocciose", done: false },
      { id: 10, name: "Egitto - Ammirare le Piramidi di Giza", done: false },
    ],
  },
  {
    id: 4,
    list: "Giochi",
    todo: [
      { id: 1, name: "Spider-Man: Miles Morales", done: true },
      { id: 2, name: "Demon's Souls", done: false },
      { id: 3, name: "Ratchet & Clank: Rift Apart", done: true },
      { id: 4, name: "Returnal", done: false },
      { id: 5, name: "Horizon Forbidden West", done: true },
      { id: 6, name: "Resident Evil Village", done: false },
      { id: 7, name: "God of War: Ragnarök", done: true },
      { id: 8, name: "Final Fantasy XVI", done: false },
      { id: 9, name: "Gran Turismo 7", done: false },
      { id: 10, name: "Elden Ring", done: false },
    ],
  },
];
